### PR TITLE
index.html: Center all elements on main page.

### PR DESCRIPTION
**Pull request by dkihe**
- Centered all elements on main page using bootstrap.
- All elements are now in a `container` div.
- Button elements and  selection bar are wrapped in `row` and `col` divs.

### CODE REVIEW

**Comment by whoodes** [comment]
Hey Damien, looks good.  Can you explain why the two commits?  I'm confused by the 'Merge branch master into issue 9' commit?

Also, it looks like you didn't pull the latest changes from master, which I updated to have jQuery requests to prevent re-routing the page to change the bulb.  So, instead of the ```action='/toggle/' method=['post']``` divs it is:

```
<form>
    <a href="#" id="turn-on">
        <button style="margin-left: 32px" 
                class="btn-outline-primary" name="ON"
                type="submit">ON
        </button>
    </a>
</form>
```

Check the master branch to see what's happening.  If I merge this, that will be over written.

**Review by whoodes — COMMENTED** [review]
Check the updated master, the forms need to be updated.

**Comment by dkihe** [comment]
The 'Merge branch master into issue 9' appeared after I had fixed any merge conflicts.  I've updated the branch so that it includes your code from the master branch.

issue-9

**Comment by whoodes** [comment]
Awesome looks good. Fixes: #9

**Pull request merged**
